# Generated by Django 5.2.17 on 2026-10-02 14:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.kaazbir.models

KAAZBIR_PROFILE_COLUMNS = [
    "id",
    "created_at",
    "updated_at",
    "user_id",
    "business_name",
    "service_category",
    "address",
    "kyc_verified",
    "service_start_time",
    "service_end_time",
    "division",
    "district",
    "upazila",
    "location",
    "is_profile_complete",
    "hourly_rate",
    "bio",
    "profile_picture",
]

KYC_COLUMNS = [
    "id",
    "created_at",
    "updated_at",
    "user_id",
    "document_type",
    "front_image",
    "back_image",
    "extracted_data",
    "consent",
    "status",
]

KYC_SELFIE_COLUMNS = [
    "id",
    "created_at",
    "updated_at",
    "kyc_id",
    "image",
    "order",
]

# Static SQL literals for non-nullable columns, used only when the source
# table predates them. Portable across PostgreSQL and SQLite.
COLUMN_FALLBACKS = {
    "kyc_verified": "FALSE",
    "is_profile_complete": "FALSE",
    "bio": "''",
    "consent": "FALSE",
    "status": "'pending'",
}


def copy_profile_data(apps, schema_editor):
    """Copy rows from the legacy ``users_*`` tables into the new ones.

    Copies only the columns that actually exist in the source table.
    Skips gracefully on fresh databases.
    """
    tables = set(schema_editor.connection.introspection.table_names())
    quote_name = schema_editor.connection.ops.quote_name
    pairs = [
        ("users_kaazbirprofile", "kaazbir_kaazbirprofile", KAAZBIR_PROFILE_COLUMNS),
        ("users_kycverification", "kaazbir_kycverification", KYC_COLUMNS),
        ("users_kycselfie", "kaazbir_kycselfie", KYC_SELFIE_COLUMNS),
    ]
    with schema_editor.connection.cursor() as cursor:
        for old_table, new_table, columns in pairs:
            if old_table not in tables or new_table not in tables:
                continue
            old_columns = {
                field.name
                for field in schema_editor.connection.introspection.get_table_description(  # noqa: E501
                    cursor, old_table
                )
            }
            insert_cols = [
                c for c in columns if c in old_columns or c in COLUMN_FALLBACKS
            ]
            if "id" not in insert_cols or (
                "user_id" not in insert_cols and "kyc_id" not in insert_cols
            ):
                continue
            select_cols = [
                quote_name(c) if c in old_columns else COLUMN_FALLBACKS[c]
                for c in insert_cols
            ]
            collist = ", ".join(quote_name(c) for c in insert_cols)
            sellist = ", ".join(select_cols)
            # All identifiers here are static migration constants,
            # never user input.
            nt, ot = quote_name(new_table), quote_name(old_table)
            query = "INSERT INTO {} ({}) SELECT {} FROM {}".format(  # nosec B608  # noqa: E501
                nt, collist, sellist, ot
            )
            cursor.execute(query)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "users",
            "0007_alter_user_role_alter_user_roles_hirermedia_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="KaazbirProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("service_category", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("kyc_verified", models.BooleanField(default=False)),
                ("service_start_time", models.TimeField(blank=True, null=True)),
                ("service_end_time", models.TimeField(blank=True, null=True)),
                ("division", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("upazila", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("is_profile_complete", models.BooleanField(default=False)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="kaazbir_profiles/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kaazbir_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KYCVerification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("passport", "Passport"),
                            ("driving_license", "Driving License"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "front_image",
                    models.ImageField(upload_to=apps.kaazbir.models.kyc_file_path),
                ),
                (
                    "back_image",
                    models.ImageField(upload_to=apps.kaazbir.models.kyc_file_path),
                ),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("consent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KYCSelfie",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.kaazbir.models.kyc_selfie_file_path
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "kyc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selfies",
                        to="kaazbir.kycverification",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RunPython(copy_profile_data, migrations.RunPython.noop),
    ]
