# Generated by Django 5.2.17 on 2026-10-04 19:50

from django.db import migrations, models

import apps.kaazbir.models


class Migration(migrations.Migration):

    dependencies = [
        ("kaazbir", "0002_kaazbirprofile_latitude_kaazbirprofile_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycverification",
            name="back_image",
            field=models.FileField(upload_to=apps.kaazbir.models.kyc_file_path),
        ),
        migrations.AlterField(
            model_name="kycverification",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("national_id", "National ID"),
                    ("passport", "Passport"),
                    ("driving_license", "Driving License"),
                    ("student_id_card", "Student ID Card"),
                    ("birth_certificate", "Birth Certificate"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="kycverification",
            name="front_image",
            field=models.FileField(upload_to=apps.kaazbir.models.kyc_file_path),
        ),
    ]
