# Generated by Django 5.2.17 on 2026-10-02 14:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

HIRER_PROFILE_COLUMNS = [
    "id",
    "created_at",
    "updated_at",
    "user_id",
    "organization_name",
    "address",
    "division",
    "district",
    "upazila",
    "location",
    "bio",
    "is_profile_complete",
    "profile_picture",
    "push_notifications",
    "sms_notifications",
    "email_notifications",
    "task_updates",
    "promotions_and_offers",
]

HIRER_MEDIA_COLUMNS = [
    "id",
    "created_at",
    "updated_at",
    "user_id",
    "media_type",
    "name",
    "picture",
]

# Static SQL literals for non-nullable columns, used only when the source
# table predates them. Portable across PostgreSQL and SQLite.
COLUMN_FALLBACKS = {
    "organization_name": "''",
    "address": "''",
    "bio": "''",
    "is_profile_complete": "FALSE",
}


def copy_hirer_data(apps, schema_editor):
    """Copy rows from the legacy ``users_*`` tables into the new ones.

    Copies only the columns that actually exist in the source table.
    Skips gracefully on fresh databases.
    """
    tables = set(schema_editor.connection.introspection.table_names())
    quote_name = schema_editor.connection.ops.quote_name
    pairs = [
        ("users_hirerprofile", "hirer_hirerprofile", HIRER_PROFILE_COLUMNS),
        ("users_hirermedia", "hirer_hirermedia", HIRER_MEDIA_COLUMNS),
    ]
    with schema_editor.connection.cursor() as cursor:
        for old_table, new_table, columns in pairs:
            if old_table not in tables or new_table not in tables:
                continue
            old_columns = {
                field.name
                for field in schema_editor.connection.introspection.get_table_description(  # noqa: E501
                    cursor, old_table
                )
            }
            insert_cols = [
                c for c in columns if c in old_columns or c in COLUMN_FALLBACKS
            ]
            if "id" not in insert_cols or "user_id" not in insert_cols:
                continue
            select_cols = [
                quote_name(c) if c in old_columns else COLUMN_FALLBACKS[c]
                for c in insert_cols
            ]
            collist = ", ".join(quote_name(c) for c in insert_cols)
            sellist = ", ".join(select_cols)
            # All identifiers here are static migration constants,
            # never user input.
            nt, ot = quote_name(new_table), quote_name(old_table)
            query = "INSERT INTO {} ({}) SELECT {} FROM {}".format(  # nosec B608  # noqa: E501
                nt, collist, sellist, ot
            )
            cursor.execute(query)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "users",
            "0007_alter_user_role_alter_user_roles_hirermedia_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HirerMedia",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("license", "License"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("picture", models.ImageField(upload_to="hirer_media/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hirer_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HirerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("division", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("upazila", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("bio", models.TextField(blank=True, default="")),
                ("is_profile_complete", models.BooleanField(default=False)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="hirer_profiles/"
                    ),
                ),
                ("push_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("task_updates", models.BooleanField(default=True)),
                ("promotions_and_offers", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hirer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(copy_hirer_data, migrations.RunPython.noop),
    ]
