# Generated by Django 5.1.15 on 2026-08-18 18:32

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_kyc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kycverification",
            name="selfie_1",
        ),
        migrations.RemoveField(
            model_name="kycverification",
            name="selfie_2",
        ),
        migrations.RemoveField(
            model_name="kycverification",
            name="selfie_3",
        ),
        migrations.RemoveField(
            model_name="kycverification",
            name="selfie_4",
        ),
        migrations.AddField(
            model_name="kaazbirprofile",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="kaazbirprofile",
            name="division",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="kaazbirprofile",
            name="is_profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kaazbirprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="kaazbirprofile",
            name="service_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kaazbirprofile",
            name="service_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kaazbirprofile",
            name="upazila",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="KYCSelfie",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=apps.users.models.kyc_selfie_file_path),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "kyc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selfies",
                        to="users.kycverification",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
