# Generated by Django 5.2.17 on 2026-08-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_kycverification_selfie_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kaazbirprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="kaazbirprofile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="kaazbirprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="kaazbir_profiles/"
            ),
        ),
    ]
