# Generated by Django 5.2.17 on 2026-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_kaazbirprofile_bio_kaazbirprofile_hourly_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("email_verification", "Email verification"),
                    ("password_reset", "Password reset"),
                ],
                default="email_verification",
                max_length=30,
            ),
        ),
    ]
