# Generated by Django 5.2.17 on 2026-09-26 18:31

from django.db import migrations, models


def backfill_roles(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user_id, role in User.objects.values_list("id", "role"):
        if role:
            User.objects.filter(pk=user_id, roles=[]).update(roles=[role])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_otp_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="All unlocked roles, e.g. ['hirer', 'kaazbir']. 'role' is the currently active entry.",  # noqa: E501
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("hirer", "Hirer"), ("kaazbir", "KaazBir")],
                default="hirer",
                help_text="Active role. One account can unlock both roles and switch between them; this field always holds the active one.",  # noqa: E501
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_roles, migrations.RunPython.noop),
    ]
