# Generated by Django 5.2.17 on 2026-09-30 02:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

HIRER_PROFILE_COLUMNS = [
    "id",
    "created_at",
    "updated_at",
    "user_id",
    "organization_name",
    "address",
    "division",
    "district",
    "upazila",
    "location",
    "bio",
    "is_profile_complete",
    "profile_picture",
    "push_notifications",
    "sms_notifications",
    "email_notifications",
    "task_updates",
    "promotions_and_offers",
]

HIRER_MEDIA_COLUMNS = [
    "id",
    "created_at",
    "updated_at",
    "user_id",
    "media_type",
    "name",
    "picture",
]

# Static SQL literals for non-nullable columns that only exist in the new
# schema. Used when the legacy table predates them (e.g. still on the
# original ``0001`` schema); portable across PostgreSQL and SQLite.
COLUMN_FALLBACKS = {
    "organization_name": "''",
    "address": "''",
    "bio": "''",
    "is_profile_complete": "FALSE",
}


def copy_hirer_data(apps, schema_editor):
    """Copy rows from the legacy ``hirer`` tables into the new ``users`` ones.

    Runs after the new tables are created. Copies only the columns that
    actually exist in the legacy table: production databases may still be on
    the original ``0001`` schema (without the Niyokdata fields), in which
    case the newer columns keep their model defaults. Skips gracefully on
    fresh databases where the legacy tables were never created.
    """
    tables = set(schema_editor.connection.introspection.table_names())
    quote_name = schema_editor.connection.ops.quote_name
    pairs = [
        ("hirer_hirerprofile", "users_hirerprofile", HIRER_PROFILE_COLUMNS),
        ("hirer_hirermedia", "users_hirermedia", HIRER_MEDIA_COLUMNS),
    ]
    with schema_editor.connection.cursor() as cursor:
        for old_table, new_table, columns in pairs:
            if old_table not in tables or new_table not in tables:
                continue
            old_columns = {
                field.name
                for field in schema_editor.connection.introspection.get_table_description(  # noqa: E501
                    cursor, old_table
                )
            }
            insert_cols = [
                c for c in columns if c in old_columns or c in COLUMN_FALLBACKS
            ]
            if "id" not in insert_cols or "user_id" not in insert_cols:
                continue
            select_cols = [
                quote_name(c) if c in old_columns else COLUMN_FALLBACKS[c]
                for c in insert_cols
            ]
            collist = ", ".join(quote_name(c) for c in insert_cols)
            sellist = ", ".join(select_cols)
            # All identifiers here are static migration constants,
            # never user input.
            nt, ot = quote_name(new_table), quote_name(old_table)
            query = "INSERT INTO {} ({}) SELECT {} FROM {}".format(  # nosec B608  # noqa: E501
                nt, collist, sellist, ot
            )
            cursor.execute(query)


def drop_legacy_hirer_tables(apps, schema_editor):
    quote_name = schema_editor.connection.ops.quote_name
    with schema_editor.connection.cursor() as cursor:
        for table in ("hirer_hirermedia", "hirer_hirerprofile"):
            cursor.execute("DROP TABLE IF EXISTS " + quote_name(table))


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_roles_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("hirer", "Hirer"), ("kaazbir", "KaazBir")],
                help_text="Active role. One account can unlock both roles and switch between them; this field always holds the active one.",  # noqa: E501
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="what is the role of the user? hirer or kaazbir?",
            ),
        ),
        migrations.CreateModel(
            name="HirerMedia",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("license", "License"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("picture", models.ImageField(upload_to="hirer_media/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hirer_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HirerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("division", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("upazila", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("bio", models.TextField(blank=True, default="")),
                ("is_profile_complete", models.BooleanField(default=False)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="hirer_profiles/"
                    ),
                ),
                ("push_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("task_updates", models.BooleanField(default=True)),
                ("promotions_and_offers", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hirer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(copy_hirer_data, migrations.RunPython.noop),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS hirer_hirermedia;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS hirer_hirerprofile;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
