# Generated by Django 5.2.17 on 2026-10-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_role_alter_user_roles_hirermedia_and_more"),
        ("kaazbir", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirerprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="kaazbirprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="kycselfie",
            name="kyc",
        ),
        migrations.RemoveField(
            model_name="kycverification",
            name="user",
        ),
        migrations.DeleteModel(
            name="HirerMedia",
        ),
        migrations.DeleteModel(
            name="HirerProfile",
        ),
        migrations.DeleteModel(
            name="KaazbirProfile",
        ),
        migrations.DeleteModel(
            name="KYCSelfie",
        ),
        migrations.DeleteModel(
            name="KYCVerification",
        ),
    ]
