# Generated by Django 5.2.17 on 2026-08-25 17:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("dropdown", "Dropdown"),
                            ("radio", "Radio"),
                            ("boolean", "Boolean"),
                            ("image", "Image Upload"),
                            ("location", "Location"),
                            ("price", "Price"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("multi_select", "Multi Select"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("placeholder", models.CharField(blank=True, max_length=255)),
                ("is_required", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubserviceCustomField",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "custom_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subservice_configs",
                        to="catalog.customfield",
                    ),
                ),
                (
                    "subservice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_configs",
                        to="catalog.subservice",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("subservice", "custom_field")},
            },
        ),
    ]
